<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCfNtTZj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCfNtTZj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCfNtTZj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCfNtTZj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCfNtTZj\App_KernelDevDebugContainer([
    'container.build_hash' => 'CfNtTZj',
    'container.build_id' => '6c18d0e7',
    'container.build_time' => 1589160157,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCfNtTZj');
