<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7mixjlU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7mixjlU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7mixjlU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7mixjlU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7mixjlU\App_KernelDevDebugContainer([
    'container.build_hash' => '7mixjlU',
    'container.build_id' => 'b3228d18',
    'container.build_time' => 1589151600,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7mixjlU');
