<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerScgLxtI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerScgLxtI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerScgLxtI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerScgLxtI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerScgLxtI\App_KernelDevDebugContainer([
    'container.build_hash' => 'ScgLxtI',
    'container.build_id' => '9374ccde',
    'container.build_time' => 1589312740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerScgLxtI');
