<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTZg7xC2\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTZg7xC2/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTZg7xC2.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTZg7xC2\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTZg7xC2\App_KernelProdContainer([
    'container.build_hash' => 'TZg7xC2',
    'container.build_id' => '26607641',
    'container.build_time' => 1589376963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTZg7xC2');
