<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD0mzFC7\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD0mzFC7/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerD0mzFC7.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerD0mzFC7\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerD0mzFC7\App_KernelProdContainer([
    'container.build_hash' => 'D0mzFC7',
    'container.build_id' => '29279a09',
    'container.build_time' => 1589312748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD0mzFC7');
