<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHJ6g1qY\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHJ6g1qY/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHJ6g1qY.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHJ6g1qY\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHJ6g1qY\App_KernelProdContainer([
    'container.build_hash' => 'HJ6g1qY',
    'container.build_id' => 'f0aedc07',
    'container.build_time' => 1589145713,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHJ6g1qY');
