<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_geolocalizacion_index' => [[], ['_controller' => 'App\\Controller\\GeolocalizacionController::index'], [], [['text', '/geolocalizacion/']], [], []],
    'app_geolocalizacion_verestadisticas' => [[], ['_controller' => 'App\\Controller\\GeolocalizacionController::verEstadisticas'], [], [['text', '/geolocalizacion/estadisticas']], [], []],
];
