<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_lucky_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky/number']], [], []],
];
